### ISSUE TITLE
Entering New event gives blank screen

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/calendar_menu#11]
Hi when i enter a new event i get a blank screen, the event is entered but there's no message about it, refreshing screen gives 2 the same entries, editing and deleting works as expected.. 

Can someone confirm or give me an clue where to look, been busy with it but no-go yet...

PhP 7, in dutch and english, e107 git from today.. 26-8-2019
Alex

**Comment by Moc** [comment]
Are you using the latest files from Github? I think I fixed this already: https://github.com/e107inc/calendar_menu/commit/76b3d23c8b0de2d763de8b57a0a49fd9fd1c3bbf

EDIT: sorry I should read your issue report better first.... Hmm, I'll continue investigating.

**Comment by Moc** [comment]
Is PDO enabled? Admin Area > PHP info, left sidebar.

**Comment by Alex-e107nl** [comment]
MySQL
5.6.27
Database: fozl01_e107v2
PDO: Aan
Mode: NO_ENGINE_SUBSTITUTION  Yess it is...

**Comment by Alex-e107nl** [comment]
Moc,
sorry it is solved, Jimmy had also some things that he had changed in his version en somehow (stupid mistake) i have mixed the 2 versions, it's woking now! The only thing is the image with a entry event on http://mydomain.com/e107_images/admin_images/forums_32.png isnt there anymore.. changed it to generic/new.png to get an arrow.... in calendar_shortcodes.php line 812

Thx for your time!
Alex

**Comment by Moc** [comment]
Ah nice! 
Yeah the old image reference is the result of an outdated plugin...
