### ISSUE TITLE
Event Calendar date problem

### ISSUE THREAD

**Issue by fizi** [e107inc/calendar_menu#4]
I use latest e107 from Github and latest event calendar menu made for v2. I had a problem-free event to insert. Now when I want insert the event - I fill in the required​ fields, enter the start and end dates of event, and I push the button GO. No event! Numbers appears instead of year on the years button. I looked the database and the date inserted wrong. If I correct the date in the database event appears on the site. (I think the datepicker - minicalendar updated in the core, but not updated in the calendar menu). The date I inserted by datepicker (mini calendar). 
![nevtelen](https://cloud.githubusercontent.com/assets/86780/17363995/f0ad8aa4-597d-11e6-80b1-277cc1b6b6e4.jpg)
![nevtelen2](https://cloud.githubusercontent.com/assets/86780/17364005/fc129696-597d-11e6-993d-121c48492394.jpg)

Thanks help!

**Comment by Moc** [comment]
Just posting it here to keep all the info in one place, from e107help.org:

> add this line 'return' => 'string',  to options for datepicker in ecal_class.php

**Comment by Batatafrita** [comment]
I was with the same problem and the fix worked and it's all perfect.

Thank you !
