### ISSUE TITLE
Error on creating new category

### ISSUE THREAD

**Issue by Crytiqal** [e107inc/calendar_menu#7]
When trying to create a new category, I receive an error upon submit.

Error
Creation Unsuccesful.

**Comment by Moc** [comment]
Seems to work here, please provide the following info which can be found on the Admin Area > About > PHP Info page (left sidebar): 

- PHP Version 
- MySQL Version
- PDO
- Mode

**Comment by Crytiqal** [comment]
It seems to work now? Sorry...
There might have been something wrong on my end.
